// sylph.idl

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C7BFFA70-552F-4B31-94DE-D7EFF741DC45),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISylphObject : IDispatch{
};

[
	uuid(8AA4CDF3-8DD4-49DC-A949-85B332FD02DC),
	version(1.0),
]
library sylphLib
{
	importlib("stdole2.tlb");
	[
		uuid(BF4D4CF8-A8E3-46FB-B52A-C746D72810AB)		
	]
	coclass SylphObject
	{
		[default] interface ISylphObject;
	};
};

